### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import re
from ydata_profiling import ProfileReport

C:\Users\speedlink\AppData\Local\Temp\ipykernel_14612\3089340042.py:4: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [2]:
category_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\Categories.csv")
sales_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\AllSales.csv")
customer_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\CustomerMaster.csv")
employees_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\Employees.csv")
products_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\ProductCatalog.csv")
stock_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\Stock.csv")
prescriptions_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\Prescriptions.csv")
stores_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\Stores.csv")
suppliers_data=pd.read_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\After Power Query\Suppliers.csv")

##### 1) All Sales Table

In [3]:
sales_data.head(10)

,Sale Id,Store Id,Employee Id,Product Id,Customer Id,Quantity,Sale Date,Unit Price,Discount Pct,Payment Method,Notes
0,187,2,32,1379,270,1,9/30/2025,148.36,4.7,Credit Card,NaN
1,308,2,89,1683,176,1,10/31/2024,117.27,9.6,Credit Card,NaN
2,482,2,23,2530,120,1,3/16/2025,270.38,9.6,Credit Card,NaN
3,509,2,28,3314,44,1,11/10/2025,176.67,7.5,Credit Card,NaN
4,527,2,28,3654,190,1,6/15/2025,33.13,3.8,Credit Card,NaN
5,545,2,43,968,64,1,2/23/2025,230.71,8.4,Credit Card,NaN
6,669,2,103,2572,1124,1,11/18/2024,14.54,10.0,Credit Card,NaN
7,749,2,103,4201,110,1,12/3/2024,155.80,9.8,Credit Card,NaN
8,976,2,23,169,2,1,11/19/2024,41.76,7.7,Credit Card,NaN
9,978,2,103,4917,1324,1,1/27/2025,135.63,3.3,Credit Card,NaN

In [4]:
sales_data.shape

(9900, 11)

In [5]:
sales_data['Notes'].unique()

array([nan, 'Promo code LOYALTY20 applied at checkout',
       'Price matched to competitor flyer',
       'Promo code SEASON25 applied at checkout',
       'Promo code SAVE10 applied at checkout',
       'Loyalty tier discount applied',
       'Promo code WELCOME15 applied at checkout'], dtype=object)

In [ ]:
profile=ProfileReport(sales_data,title="Sales Data Report",explorative=True)
profile.to_file("sales_data_report.html")
profile

In [7]:
def extract_promo(note):
    if pd.isna(note) or note=="":
        return pd.Series({"Promo Code":None, "Discount Reason":None})
    promo_code_match=re.search(r'Promo code (\w+) applied at checkout',note)
    if promo_code_match:
        return pd.Series({"Promo Code":promo_code_match.group(1), "Discount Reason":'Promo code'})
    if 'competitor' in note.lower():
        return pd.Series({"Promo Code":None, "Discount Reason":'Competitor Price Match'})
    if 'Loyalty' in note:
        return pd.Series({"Promo Code":None, "Discount Reason":'Loyalty Discount'})
    return pd.Series({"Promo Code":None, "Discount Reason":'other'})

extracted=sales_data['Notes'].apply(extract_promo)
sales_data=pd.concat([sales_data,extracted],axis=1)

In [8]:
sales_data.drop(columns=['Notes'],inplace=True)

In [9]:
sales_data.head(10)

,Sale Id,Store Id,Employee Id,Product Id,Customer Id,Quantity,Sale Date,Unit Price,Discount Pct,Payment Method,Promo Code,Discount Reason
0,187,2,32,1379,270,1,9/30/2025,148.36,4.7,Credit Card,None,None
1,308,2,89,1683,176,1,10/31/2024,117.27,9.6,Credit Card,None,None
2,482,2,23,2530,120,1,3/16/2025,270.38,9.6,Credit Card,None,None
3,509,2,28,3314,44,1,11/10/2025,176.67,7.5,Credit Card,None,None
4,527,2,28,3654,190,1,6/15/2025,33.13,3.8,Credit Card,None,None
5,545,2,43,968,64,1,2/23/2025,230.71,8.4,Credit Card,None,None
6,669,2,103,2572,1124,1,11/18/2024,14.54,10.0,Credit Card,None,None
7,749,2,103,4201,110,1,12/3/2024,155.80,9.8,Credit Card,None,None
8,976,2,23,169,2,1,11/19/2024,41.76,7.7,Credit Card,None,None
9,978,2,103,4917,1324,1,1/27/2025,135.63,3.3,Credit Card,None,None

In [10]:
sales_data['Discount Reason'].value_counts(dropna=False)

Discount Reason
None                      8268
Promo code                 841
Competitor Price Match     456
Loyalty Discount           335
Name: count, dtype: int64

##### 2) Customer Master Table

In [11]:
customer_data.head(10)

,Customer Id,Full Name,Email,Phone,City,Signup Date,Notes
0,943,Jason Nguyen,jasonnguyen943@hotmail.com,(177) 788-9646,TORONTO,3/26/2021,NaN
1,645,Michelle Chan,michelle.chan645@gmail.com,9612734670,TORONTO,4/25/2022,NaN
2,1004,Jennifer Smith,jennifer_smith1004@outlook.com,425-381-0689,TORONTO,8/23/2022,NaN
3,249,James Singh,jamessingh249@yahoo.com,(517) 845-3144,TORONTO,9/27/2022,NaN
4,1046,Michael Wilson,michael_wilson1046@yahoo.com,3511582388,TORONTO,4/11/2023,NaN
5,1532,Susan Cllark,susan_cllark1532@gmail.com,(251) 983-6473,TORONTO,12/6/2022,NaN
6,629,Robert White,robert.white629@yahoo.com,(886) 784-1047,TORONTO,7/30/2024,NaN
7,992,Mary Gagnon,marygagnon992@outlook.com,944.547.3221,TORONTO,10/22/2020,NaN
8,322,Joseph Taylor,joseph.taylor322@yahoo.com,981.019.4771,TORONTO,3/14/2021,NaN
9,182,Jessica Clark,jessica_clark182@outlook.com,1918453122,TORONTO,5/4/2019,NaN

In [12]:
customer_data['Notes'].unique()

array([nan, 'Prefers text reminders', 'Opted out of email marketing',
       'Gold member - loyalty since 2024',
       'Gold member - loyalty since 2020',
       'Platinum member - loyalty since 2022',
       'Gold member - loyalty since 2021',
       'Gold member - loyalty since 2023', 'Requested large-print labels',
       'Prefers pickup, not delivery',
       'Platinum member - loyalty since 2021',
       'Silver member - loyalty since 2022',
       'Silver member - loyalty since 2019',
       'Gold member - loyalty since 2025',
       'Gold member - loyalty since 2019',
       'Platinum member - loyalty since 2023',
       'Silver member - loyalty since 2021',
       'Silver member - loyalty since 2024',
       'Platinum member - loyalty since 2024',
       'Platinum member - loyalty since 2019',
       'Silver member - loyalty since 2023',
       'Silver member - loyalty since 2020',
       'Platinum member - loyalty since 2020',
       'Platinum member - loyalty since 2025',
       'Silver member - loyalty since 2025',
       'Gold member - loyalty since 2022'], dtype=object)

In [13]:
def extract_loyalty(note):
    if pd.isnull(note) or note ==" ":
        return pd.Series({'Loyalty Tier':None , 'Loyalty Since':None})
    loyalty_tier_match=re.search(r'(Silver|Gold|Platinum) member - loyalty since (\d{4})',note)
    if loyalty_tier_match:
        return pd.Series({'Loyalty Tier':loyalty_tier_match.group(1), 'Loyalty Since':int(loyalty_tier_match.group(2))})
    return pd.Series({'Loyalty Tier':None , 'Loyalty Since':None})

extracted_loyalty=customer_data['Notes'].apply(extract_loyalty)
customer_data=pd.concat([customer_data,extracted_loyalty],axis=1)

In [14]:
customer_data.head(10)

,Customer Id,Full Name,Email,Phone,City,Signup Date,Notes,Loyalty Tier,Loyalty Since
0,943,Jason Nguyen,jasonnguyen943@hotmail.com,(177) 788-9646,TORONTO,3/26/2021,NaN,None,NaN
1,645,Michelle Chan,michelle.chan645@gmail.com,9612734670,TORONTO,4/25/2022,NaN,None,NaN
2,1004,Jennifer Smith,jennifer_smith1004@outlook.com,425-381-0689,TORONTO,8/23/2022,NaN,None,NaN
3,249,James Singh,jamessingh249@yahoo.com,(517) 845-3144,TORONTO,9/27/2022,NaN,None,NaN
4,1046,Michael Wilson,michael_wilson1046@yahoo.com,3511582388,TORONTO,4/11/2023,NaN,None,NaN
5,1532,Susan Cllark,susan_cllark1532@gmail.com,(251) 983-6473,TORONTO,12/6/2022,NaN,None,NaN
6,629,Robert White,robert.white629@yahoo.com,(886) 784-1047,TORONTO,7/30/2024,NaN,None,NaN
7,992,Mary Gagnon,marygagnon992@outlook.com,944.547.3221,TORONTO,10/22/2020,NaN,None,NaN
8,322,Joseph Taylor,joseph.taylor322@yahoo.com,981.019.4771,TORONTO,3/14/2021,NaN,None,NaN
9,182,Jessica Clark,jessica_clark182@outlook.com,1918453122,TORONTO,5/4/2019,NaN,None,NaN

In [15]:
customer_data['Loyalty Tier'].value_counts(dropna=False)

Loyalty Tier
None        1099
Silver       158
Platinum     154
Gold         144
Name: count, dtype: int64

In [16]:
customer_data.drop(columns=['Notes'],inplace=True)

In [17]:
customer_data['City'].unique()

array(['TORONTO', 'Vancouver', 'Calgary', 'Montreal', 'Winnipeg, MB',
       'waterloo', 'Quebec City', 'Winnipeg', 'Vancouver, BC', 'Edmonton',
       'Halifax', 'Moncton', 'Saskatoon', 'Ottawa, ON', 'Montreal, QC',
       'London', 'Regina', 'Ottawa', 'Kitchener', 'Hamilton',
       'Calgary, AB', 'Quebec', 'Edmonton, AB', 'Vancouvr', 'QC City',
       'Regina, SK', 'Montréal', 'Halifax, NS', 'Waterloo, ON',
       'Toronto, ON', 'Trnto', 'Moncton, NB'], dtype=object)

In [18]:
# Cleaning the 'City' column by removing leading/trailing spaces and duplicates formats 
customer_data['City Clean']=customer_data['City'].astype(str).str.split(',').str[0].str.strip().str.title()

In [19]:
customer_data['City Clean'].unique()

array(['Toronto', 'Vancouver', 'Calgary', 'Montreal', 'Winnipeg',
       'Waterloo', 'Quebec City', 'Edmonton', 'Halifax', 'Moncton',
       'Saskatoon', 'Ottawa', 'London', 'Regina', 'Kitchener', 'Hamilton',
       'Quebec', 'Vancouvr', 'Qc City', 'Montréal', 'Trnto'], dtype=object)

In [20]:
customer_data['Phone'].unique()

array(['(177) 788-9646', '9612734670', '425-381-0689', ..., '5896937041',
       '3283459480', '1167412093'], dtype=object)

In [21]:
# Cleaning the 'Phone' column by removing non-digit characters
customer_data['Phone Clean']=customer_data['Phone'].astype(str).str.replace(r'\D','',regex=True)

In [22]:
customer_data['Phone Clean']

0       1777889646
1       9612734670
2       4253810689
3       5178453144
4       3511582388
           ...
1550    8904907151
1551    1925853016
1552    5896937041
1553    3283459480
1554    1167412093
Name: Phone Clean, Length: 1555, dtype: object

In [23]:
customer_data['Full Name'].unique()

array(['Jason Nguyen', 'Michelle Chan', 'Jennifer Smith', 'James Singh',
       'Michael Wilson', 'Susan Cllark', 'Robert White', 'Mary Gagnon',
       'Joseph Taylor', 'Jessica Clark', 'Emily Lee', 'Emily Young',
       'Daniel White', 'John Roy', 'David Martin', 'Jessica Singh',
       'Sarah Clark', 'Brian Campbell', 'Linda Hall', 'Jason Young',
       'Sarah Tremblay', 'Sarah MacDonald', 'Joseph Campbell',
       'Laura Taylor', 'Laura Hall', 'Matthew Smith', 'Andrew White',
       'Lisa Brown', 'Susan Chan', 'Lisa Martin', 'Laura Patel',
       'Jennifer Gagnon', 'Amanda Chan', 'Linda Taylor', 'Robert Gagnon',
       'Elizabeth Nguyen', 'Patricia Hall', 'Susan MacDonald',
       'Brian Brown', 'Justin Hall', 'Sarah Brown', 'John Clark',
       'Karen Tremblay', 'Amanda Anderson', 'Kevin Campbell',
       'Emily Taylor', 'Emily Tremblay', 'Karen Campbell', 'Laura White',
       'John Brown', 'Jessica Brown', 'Jennifer Wilson', 'Susan Wilson',
       'Daniel Singh', 'Joseph Singh', 'Patricia Campbell',
       'Jessica Smith', 'Robert Roy', 'Matthew MacDonald', 'Daniel Patel',
       'Brandon White', 'Susan Brown', 'Andrew Hall', 'Michael Roy',
       'James MacDonald', 'Mary Singh', 'Mary Anderson',
       'Michael Campbell', 'Elizabeth Gagnon', 'Jennifer White',
       'Michelle Smith', 'Susan Clark', 'Brian MacDonald',
       'Brandon Tremblay', 'Robert Tremblay', 'Laura Young',
       'Michelle Clark', 'Ryan Clark', 'Ryan Chan', 'James Chan',
       'John Gagnon', 'Kevin Roy', 'Ryan Nguyen', 'David Singh',
       'James Anderson', 'Jessica Anderson', 'James Tremblay',
       'James Brown', 'Kevin Wilson', 'Sarah Singh', 'Laura Chan',
       'John White', 'Ryan Patel', 'Sarah Gagnon', 'Michelle Gagnon',
       'Jennifer Campbell', 'Daniel Anderson', 'Joseph Patel',
       'Brian Gagnon', 'Susan Lee', 'Emily Nguyen', 'John Young',
       'Michelle Patel', 'Susan Hall', 'Michelle Anderson',
       'Michelle Taylor', 'Sarah Nguyen', 'Jennifer Tremblay',
       'Lisa Tremblay', 'Emily Patel', 'Laura Anderson', 'Sarah Smith',
       'Amanda Lee', 'Amanda Martin', 'Lisa White', 'Patricia Clark',
       'Joseph Anderson', 'Kevin Martin', 'Jason Hall', 'Daniel Nguyen',
       'Mary Roy', 'Kevin Tremblay', 'Laura Wilson', 'JJason Chan',
       'Andrew Campbell', 'Kevin Chan', 'Ryan Singh', 'Amanda MacDonald',
       'Lisa Young', 'Matthew Young', 'Michael Brown', 'Michelle Wilson',
       'Kevin Young', 'Daniel Roy', 'Liisa Young', 'Mary Patel',
       'Matthew Singh', 'John Martin', 'Patricia Patel', 'Linda Roy',
       'Jennifer Lee', 'Jessica Wilson', 'Michael Patel',
       'Justin Anderson', 'James Smith', 'Amanda Young', 'John Taylor',
       'Linda White', 'Kevin Smith', 'Jason Chan', 'Daniel Brown',
       'Robert Taylor', 'Laura Campbell', 'Daniel Smith', 'Emily White',
       'Karen Clark', 'Robert Patel', 'Laura Nguyen', 'Jessica Lee',
       'Nancy Campbeell', 'Lisa Clark', 'David Lee', 'Nancy White',
       'Lisa Chan', 'David Roy', 'David Brown', 'David Chan',
       'Patricia Anderson', 'Daniel Wilson', 'Patricia Nguyen',
       'Mary Hall', 'Patricia White', 'Nancy Campbell', 'Ryan Siingh',
       'Nancy Brown', 'Karen MacDonald', 'Daniel Lee', 'Nancy Wilson',
       'Ryan Roy', 'Karen Brown', 'Andrew Smith', 'Patricia Chan',
       'James Taylor', 'Justin Taylor', 'Lisa Smith', 'David MacDonald',
       'Jason Wilson', 'Robert Smith', 'David Smith', 'Jason Tremblay',
       'Brian Roy', 'Sarah Anderson', 'Matthew White', 'Amanda BBrown',
       'Jessica Taylor', 'Michael Lee', 'Robert Anderson', 'Kevin Brown',
       'Emily Martin', 'Laura Clark', 'John Wilson', 'Joseph Hall',
       'Lisa Wilson', 'Michael Nguyen', 'Andrew Wilson', 'Miichael Chan',
       'Josseph Hall', 'Mary Nguyen', 'Jessica Martin', 'Justin Young',
       'Emily Hall', 'Daniel Clark', 'Amanda Roy', 'Jennifer Nguyen',
       'Andrew Singh', 'Matthew Clark', 'Andrew Anderson', 'Susan Young',
       'Andrew Clark', 'Kevin White', 'Linda Patel', 'Jennifer Taylor',
       'Ryan Tremblay', 'Elizabeth Clark', 'Ryan Gagnon', 'Brandon Singh',
       'Emily Brown', 'Robert Lee', 'Elizabeth Anderson', 'Lisa Anderson',
       'Jason Patel', 'Justin Singh', 'Amanda Brown', 'Michael Chan',
       'Jennifer Roy', 'David Hall', 'John Campbell', 'Nancy Taaylor',
       'Daniel MacDonald', 'Lisa Patel', 'Elizabeth Campbell',
       'Elizabeth Tremblay', 'Nancy MacDonald', 'Michelle Martin',
       'Robert Hall', 'Jason Smith', 'Amanda Taylor', 'Susan Smith',
       'Karen Nguyen', 'Linda Singh', 'Justin Brown', 'Brandon Martin',
       'Matthew Nguyen', 'David Young', 'Karen Hall', 'Nancy Taylor',
       'Lisa MacDonald', 'Daniel Taylor', 'Michael Taylor',
       'Justin MacDonald', 'Jennifer Brown', 'Karen Patel',
       'Brandon Brown', 'Emily Chan', 'Laura Brown', 'Justin Campbell',
       'Jennifer Clark', 'Brandon Gagnon', 'Daniel Campbell', 'Laura Lee',
       'Joseph Wilson', 'Michael White', 'Daniel Martin',
       'Daniel Taylorr', 'Michael Gagnon', 'Robert Nguyen',
       'Patricia Singh', 'Karen Wilson', 'Brian Chan', 'David Gagnon',
       'Ryyan Anderson', 'Jessica Nguyen', 'Brandon Hall', 'Emily Gagnon',
       'Lisa Gagnon', 'Justin Chan', 'Susan Roy', 'Michelle Lee',
       'Nancy Gagnon', 'Nancy Hall', 'Keevin Young', 'Brandon Lee',
       'Jason Roy', 'Laura Leee', 'Robert Clark', 'Elizabeth Singh',
       'Nancy Roy', 'Brian Wilson', 'Brian White', 'Michelle Nguyen',
       'Kevin Lee', 'Kevin MacDonald', 'Mary Brown', 'Amanda Wilson',
       'James Martin', 'Amanda Clark', 'Brian Smith', 'Brian Clark',
       'Brandon Chan', 'Amanda Patel', 'RRobert MacDonald', 'Sarah Patel',
       'Michael Young', 'Michelle White', 'Anddrew Taylor', 'Nancy Singh',
       'Ryan Lee', 'Joseph Chan', 'Joseph Young', 'Kevin Hall',
       'Laura Martin', 'Joseph Tremblay', 'Andrew Taylor', 'Justin Lee',
       'John Lee', 'John Nguyen', 'Kevin Nguyen', 'John Anderson',
       'Susan White', 'Patricia Tremblay', 'Robert Singh', 'Justin Patel',
       'Michelle Hall', 'Patricia Taylor', 'Elizabeth Wilson',
       'Patricia Wilson', 'Jessica Gagnon', 'Jessica Young',
       'Jennifer Singh', 'Matthew Roy', 'Joseph Nguyen', 'Sarah Hall',
       'Amanda Nguyen', 'Brandon Campbell', 'Karen Anderson',
       'Ryan Smith', 'Lisa Singh', 'Nancy Young', 'Michael Paatel',
       'Mary Wilson', 'James White', 'Jason White', 'David Anderson',
       'Ryan Anderson', 'Linda Smith', 'Amanda Campbell', 'James Nguyen',
       'Robert Martin', 'John Chan', 'Michelle MacDonald',
       'Susan Campbell', 'Mary MacDonald', 'Michael MacDonald',
       'Jason Campbell', 'Sarrah Chan', 'Joseph Lee', 'Jason Gagnon',
       'Brian Martin', 'Michelle Young', 'Kevin Singh', 'Ryan Martin',
       'David Taylor', 'Amanda Hall', 'Matthew Campbell',
       'Linda MacDonald', 'Jessica White', 'Nancy Martin', 'David Wilson',
       'Ryann Singh', 'Pattricia Taylor', 'Linda Wilson', 'Ryan Wilson',
       'Mary Lee', 'Brandon Wilson', 'Mary Clark', 'Lisa Lee',
       'Justin Gagnon', 'Jessica MacDonald', 'Emily Anderson',
       'Lisa Campbell', 'Elizabeth Lee', 'Briaan Wilson', 'Ryan Campbell',
       'Jason Taylor', 'Jessica Roy', 'Lisa Nguyen', 'Justin Tremblay',
       'Brian Lee', 'David Patel', 'Robert MacDonald', 'Linda Martin',
       'Jason MacDonald', 'Karen Young', 'Jennifer Chan', 'Karen Lee',
       'James Campbell', 'Susan Gagnon', 'Kevin Anderson',
       'Jennifer MacDonald', 'Brian Patel', 'David Campbell',
       'Sarah Young', 'Sarah Tremblaay', 'Matthew Wilson',
       'John MacDonald', 'Jessica Patel', 'Linda Young', 'Matthew Lee',
       'Andrew Chan', 'Laura Smith', 'Mary Taylor', 'Nancy Nguyen',
       'Jennifer Martin', 'Mary Martin', 'Linda Chan', 'Matthew Brown',
       'David White', 'Andrew Roy', 'Laura Singh', 'Jessica Gaagnon',
       'Justin Nguyen', 'Brian Singh', 'Patricia Lee', 'Karen Martin',
       'Mary Smith', 'Jennifer Anderson', 'Patricia Martin',
       'Emily MacDonald', 'Joseph Youung', 'Jennifer Patel', 'Karen Chan',
       'Robert Wilson', 'Brian Tremblay', 'Ryan Young', 'Jason Clark',
       'Linda Brown', 'Andrew MacDonald', 'Mary White', 'Linda Nguyen',
       'Jusstin Gagnon', 'Jessica Tremblay', 'Joseph YYoung',
       'Susan Martin', 'Karen Roy', 'Patricia Roy', 'Matthew Hall',
       'John Whhite', 'Elizabeth Hall', 'John Singh', 'Daniel Gagnon',
       'Daniel Young', 'John Tremblay', 'Brandon Clark', 'Justin White',
       'Michelle Campbell', 'Ryan White', 'Linda Lee', 'James Trembllay',
       'Laura MacDonald', 'Elizabeth Roy', 'Nancy Smith', 'Brian Young',
       'Mary Chan', 'Matthew Anderson', 'Elizabeth Taylor',
       'Patricia Smith', 'John Patel', 'Patricia Brown', 'James Roy',
       'Robert Chan', 'Andrew Gagnon', 'Robert Brown', 'Elizabeth White',
       'Emily Smith', 'Michael Anderson', 'Daniel Tremblay', 'Sarah Chan',
       'Justin Wilson', 'Laura Gagnon', 'Daniel Cammpbell',
       'Brian Anderson', 'Joseph Roy', 'Kevin Halll', 'James Young',
       'Jason Anderson', 'Andrew Young', 'Matthew Tremblay',
       'Amanda White', 'Robert Campbell', 'Matthew MacDonnald',
       'Joseph Smith', 'Patricia MacDonald', 'Justin Clark',
       'James Patel', 'Elizabeth Chan', 'Michelle Tremblay',
       'Patricia Gagnon', 'Joseph Gagnon', 'Jessica Hall', 'James Hall',
       'Nancy Lee', 'Nancy Patel', 'Ryan MacDonald', 'Ryan Taylor',
       'Andrew Brown', 'Lisa Taylor', 'Michelle Roy', 'Mary Campbell',
       'Michael Tremblay', 'Jessica Chan', 'Lisa Roy', 'Michael Smith',
       'Brian Taylor', 'Daniel Gaagnon', 'Daniel Trremblay',
       'Karen Smith', 'Robert Young', 'Susan Singh', 'Karen Gagnon',
       'Brandon Nguyen', 'Matthew Patel', 'Nancy WWhite', 'Mary Young',
       'Susan Nguyen', 'Kevin Patel', 'Karenn Patel', 'Justin Smith',
       'Josseph Brown', 'Jason Lee', 'Matthew Taylor', 'Laura Roy',
       'Mary Tremblay', 'Elizabeth Smith', 'Brandon Patel',
       'Emily Wilson', 'Nancy Maartin', 'Amanda Tremblay', 'Joseph Brown',
       'Sarah Lee', 'David Tremblay', 'Joseph Clark', 'Brandon Taylor',
       'David Nguyen', 'Andrew Patel', 'Andrew Martin', 'Lisa Hall',
       'Kevin Gagnon', 'Emilyy Taylor', 'Daniel Hall', 'Karen Taylor',
       'Nancy Chan', 'Elizabeth Martin', 'Brian Hall', 'Linda Campbell',
       'Andrew Lee', 'James Lee', 'Michaell Gagnon', 'Jennifer Hall',
       'Amanda Singh', 'Sarah Taylor', 'Susan Singhh', 'Linda Clark',
       'Sarah White', 'Emily Singh', 'Jessica Campbell',
       'Branddon Tremblay', 'James Wilson', 'Jamees Patel', 'Karen Singh',
       'Matthew Martin', 'David Clark', 'James Halll', 'Justinn Tremblay',
       'Sarah Roy', 'Patriciia Smith', 'Briaan White', 'Emily Campbell',
       'John Hall', 'Karen White', 'Matthew Chan', 'RRyan Chan',
       'Branndon Taylor', 'Brian Nguyen', 'Michelle Brown',
       'Jason Martin', 'Nancy Anderson', 'Susan Patel', 'Emily Roy',
       'Michael Singh', 'Elizabeth Patel', 'James Andersson',
       'Elizabeth Young'], dtype=object)

In [24]:
# Check the number of duplicate phone numbers in the 'Phone Clean' column
duplicates_groups=[
    {
        'phone': phone,
        'customer_ids':group['Customer Id'].tolist()
    }

    for phone,group in customer_data.groupby('Phone Clean')
    if len(group)>1
]

duplicates_groups

[{'phone': '0120312738', 'customer_ids': [1529, 1368]},
 {'phone': '0346718657', 'customer_ids': [1523, 1262]},
 {'phone': '0903958146', 'customer_ids': [227, 1539]},
 {'phone': '0940211340', 'customer_ids': [1544, 843]},
 {'phone': '1070983552', 'customer_ids': [1288, 1551]},
 {'phone': '1232566042', 'customer_ids': [11, 1507]},
 {'phone': '1387506072', 'customer_ids': [1511, 490]},
 {'phone': '1403780254', 'customer_ids': [201, 1545]},
 {'phone': '1918453122', 'customer_ids': [182, 1502]},
 {'phone': '2082302039', 'customer_ids': [92, 1542]},
 {'phone': '2364021542', 'customer_ids': [1505, 1308]},
 {'phone': '2519836473', 'customer_ids': [1532, 43]},
 {'phone': '2719200342', 'customer_ids': [1536, 1363]},
 {'phone': '2861539636', 'customer_ids': [1543, 872]},
 {'phone': '2930495031', 'customer_ids': [1541, 1492]},
 {'phone': '3070107286', 'customer_ids': [1518, 1453]},
 {'phone': '3100486159', 'customer_ids': [85, 1517]},
 {'phone': '3122820605', 'customer_ids': [1525, 426]},
 {'phone': '3350119341', 'customer_ids': [136, 1510]},
 {'phone': '3914256511', 'customer_ids': [732, 1554]},
 {'phone': '3991931598', 'customer_ids': [232, 1548]},
 {'phone': '4453111141', 'customer_ids': [1527, 1327]},
 {'phone': '4554728484', 'customer_ids': [837, 1524]},
 {'phone': '5156393203', 'customer_ids': [806, 1552]},
 {'phone': '5213537876', 'customer_ids': [1187, 1533]},
 {'phone': '5560399891', 'customer_ids': [1508, 1346]},
 {'phone': '6091391101', 'customer_ids': [1509, 220]},
 {'phone': '6296743145', 'customer_ids': [1512, 1147]},
 {'phone': '6474935237', 'customer_ids': [704, 1503]},
 {'phone': '6480297227', 'customer_ids': [1226, 1504]},
 {'phone': '6592169945', 'customer_ids': [1513, 446]},
 {'phone': '6619577471', 'customer_ids': [731, 1553]},
 {'phone': '6819081876', 'customer_ids': [1534, 411]},
 {'phone': '7110878738', 'customer_ids': [1546, 366]},
 {'phone': '7508920694', 'customer_ids': [1351, 1528]},
 {'phone': '7624741910', 'customer_ids': [1535, 1138]},
 {'phone': '7630544575', 'customer_ids': [1506, 518]},
 {'phone': '7821678948', 'customer_ids': [1501, 86]},
 {'phone': '8408967147', 'customer_ids': [29, 1515]},
 {'phone': '8982484003', 'customer_ids': [1540, 280]},
 {'phone': '9091405791', 'customer_ids': [1550, 742]},
 {'phone': '9507472950', 'customer_ids': [159, 1514]}]

In [25]:
# # Dropping duplicate rows based on the 'Phone Clean' column
# customer_data=customer_data.drop_duplicates(subset='Phone Clean',keep='first')

##### 3) Employees Table

In [26]:
employees_data.head(10)

,Employee Id,Store Id,Employee Name,Email,Position,Salary,Hire Date,Is Pharmacist
0,1,4,Staff Member 1,staff_member_1@company.com,Sales Associate,8830.50,5/6/2020,0
1,2,9,Staff Member 2,staff_member_2@company.com,Inventory Specialist,6570.51,5/27/2024,0
2,3,1,Staff Member 3,staff_member_3@company.com,Inventory Specialist,6690.47,12/3/2023,0
3,4,1,Staff Member 4,staff_member_4@company.com,Sales Associate,4809.30,10/13/2019,1
4,5,7,Staff Member 5,staff_member_5@company.com,Sales Associate,8930.54,1/4/2018,0
5,6,9,Staff Member 6,staff_member_6@company.com,Inventory Specialist,5889.70,4/29/2020,0
6,7,7,Staff Member 7,staff_member_7@company.com,Inventory Specialist,5187.55,2/8/2018,0
7,8,2,Staff Member 8,staff_member_8@company.com,Store Manager,7443.98,10/22/2023,0
8,9,8,Staff Member 9,staff_member_9@company.com,Inventory Specialist,9289.79,8/22/2024,1
9,10,2,Staff Member 10,staff_member_10@company.com,Pharmacist,6057.50,11/11/2018,1

In [27]:
employees_data.loc[
    employees_data['Is Pharmacist'] == 0,
    ['Position', 'Is Pharmacist']
]

                 Position  Is Pharmacist
0         Sales Associate              0
1    Inventory Specialist              0
2    Inventory Specialist              0
4         Sales Associate              0
5    Inventory Specialist              0
..                    ...            ...
114            Technician              0
115       Sales Associate              0
116            Pharmacist              0
118         Store Manager              0
119            Technician              0

[93 rows x 2 columns]

In [28]:
employees_data['Position'].unique()

array(['Sales Associate', 'Inventory Specialist', 'Store Manager',
       'Pharmacist', 'Technician'], dtype=object)

In [29]:
employees_data['Is Pharmacist'] = (
    employees_data['Position'] == 'Pharmacist'
).astype(int)

In [30]:
employees_data['Is Pharmacist'].value_counts()

Is Pharmacist
0    100
1     20
Name: count, dtype: int64

##### 4) Product Catalog Table

In [31]:
products_data.head(10)

,Product Id,Product Name,Category Id,Supplier Id,Unit Price,Cost Price,Brand,Expiry Date,Storage Condition,Created At,Pack Info
0,2,Health Product 2,8,3,111.42,64.75,MediCare,8/8/2026,Refrigerated,9/13/2022,NaN
1,39,Health Product 39,9,5,34.55,21.04,BioZen,12/29/2025,Refrigerated,8/6/2025,NaN
2,51,Health Product 51,3,2,146.82,89.56,CuraMax,9/17/2026,Refrigerated,9/7/2025,NaN
3,76,Health Product 76,1,3,154.35,60.18,LifeLine,8/23/2026,Refrigerated,9/3/2024,NaN
4,123,Health Product 123,8,4,299.65,174.20,CuraMax,11/12/2028,Refrigerated,10/31/2025,NaN
5,136,Health Product 136,4,1,208.37,138.08,PharmaCo,10/8/2026,Refrigerated,11/30/2021,NaN
6,255,Health Product 255,1,2,94.36,34.91,LifeLine,11/17/2028,Refrigerated,12/20/2022,NaN
7,303,Health Product 303,6,4,262.69,133.45,CuraMax,5/20/2026,Refrigerated,10/28/2023,NaN
8,352,Health Product 352,7,4,16.99,8.02,HealthPlus,12/8/2029,Refrigerated,4/10/2025,NaN
9,360,Health Product 360,2,4,37.57,15.69,HealthPlus,11/4/2026,Refrigerated,8/23/2024,NaN

In [32]:
products_data['Pack Info'].unique()

array([nan, 'Pack: 300ml | Strength: 250mg|5ml | Form: Liquid',
       'Pack: 90g | Form: Cream',
       'Pack: 20 tabs | Strength: 250mg | Form: Tablet',
       'Pack: 60g | Form: Cream',
       'Pack: 20 tabs | Strength: 50mg | Form: Tablet',
       'Pack: 20 units | Form: Kit', 'Pack: 100 units | Form: Kit',
       'Pack: 90 tabs | Strength: 50mg | Form: Tablet',
       'Form: Liquid | Pack: 150ml | Strength: 50mg|5ml',
       'Pack: 30 caps | Strength: 25mg | Form: Capsule',
       'Pack: 30 tabs | Strength: 650mg | Form: Tablet',
       'Pack: 30 tabs | Strength: 250mg | Form: Tablet',
       'Pack: 30 tabs | Strength: 25mg | Form: Tablet',
       'Pack: 100 tabs | Strength: 250mg | Form: Tablet', 'Form: Device',
       'Pack: 450ml | Strength: 25mg|5ml | Form: Liquid',
       'Pack: 30g | Form: Cream',
       'Pack: 60 tabs | Strength: 100mg | Form: Tablet', 'Pack: 10g',
       'Pack: 20g | Form: Cream', 'Pack: 90g | Form: Bandage',
       'Pack: 30 caps | Strength: 500mg | Form: Capsule',
       'Pack: 60 tabs | Strength: 500mg | Form: Tablet',
       'Pack: 20g | Form: Bandage',
       'Pack: 20 tabs | Strength: 200mg | Form: Tablet',
       'Pack: 30g | Form: Bandage', 'Pack: 90 units | Form: Kit',
       'Form: Device | Warranty: 6m',
       'Pack: 150ml | Strength: 200mg|5ml | Form: Liquid',
       'Form: Cream | Pack: 60g', 'Pack: 100g | Form: Cream',
       'Pack: 10g | Form: Bandage',
       'Pack: 30 tabs | Strength: 500mg | Form: Tablet', 'Pack: 30g',
       'Form: Device | Warranty: 24m',
       'Pack: 100 tabs | Strength: 650mg | Form: Tablet',
       'Strength: 500mg | Form: Tablet | Pack: 60 tabs',
       'Pack: 60 units | Form: Kit',
       'Pack: 30 caps | Strength: 100mg | Form: Capsule',
       'Pack: 60 caps | Strength: 200mg | Form: Capsule',
       'Form: Device | Warranty: 12m', 'Pack: 10g | Form: Cream',
       'Pack: 100ml | Strength: 100mg|5ml | Form: Liquid',
       'Pack: 10 units | Form: Kit', 'Pack: 30 units | Form: Kit',
       'Form: Bandage | Pack: 10g',
       'Pack: 90 tabs | Strength: 25mg | Form: Tablet',
       'Pack: 500ml | Strength: 500mg|5ml',
       'Pack: 10 tabs | Strength: 100mg | Form: Tablet',
       'Strength: 200mg | Form: Capsule | Pack: 100 caps',
       'Pack: 60g | Form: Bandage',
       'Strength: 50mg|5ml | Form: Liquid | Pack: 300ml',
       'Pack: 90 caps | Strength: 500mg | Form: Capsule',
       'Pack: 500ml | Strength: 650mg|5ml | Form: Liquid',
       'Pack: 100g | Form: Bandage', 'Form: Cream | Pack: 30g',
       'Warranty: 6m | Form: Device',
       'Pack: 100 tabs | Strength: 50mg | Form: Tablet', 'Pack: 100g',
       'Pack: 60 units', 'Strength: 50mg | Pack: 30 tabs',
       'Form: Capsule | Strength: 200mg | Pack: 20 caps',
       'Strength: 650mg | Pack: 10 tabs',
       'Pack: 90 tabs | Strength: 650mg',
       'Strength: 100mg|5ml | Pack: 50ml | Form: Liquid',
       'Pack: 100 tabs | Strength: 25mg', 'Pack: 20g',
       'Pack: 20 tabs | Strength: 650mg | Form: Tablet',
       'Form: Cream | Pack: 90g',
       'Pack: 60 tabs | Form: Tablet | Strength: 200mg',
       'Pack: 30 tabs | Strength: 50mg',
       'Strength: 200mg | Form: Capsule | Pack: 60 caps',
       'Pack: 100 caps | Strength: 200mg | Form: Capsule',
       'Pack: 20 tabs | Strength: 25mg | Form: Tablet',
       'Pack: 20 caps | Strength: 650mg | Form: Capsule',
       'Pack: 10 caps | Strength: 25mg | Form: Capsule',
       'Pack: 100 tabs | Strength: 100mg | Form: Tablet',
       'Strength: 25mg|5ml | Form: Liquid | Pack: 500ml',
       'Form: Liquid | Strength: 50mg|5ml | Pack: 300ml',
       'Pack: 150ml | Strength: 50mg|5ml | Form: Liquid',
       'Pack: 450ml | Strength: 250mg|5ml',
       'Pack: 60 tabs | Strength: 200mg | Form: Tablet',
       'Pack: 10 tabs | Strength: 500mg | Form: Tablet',
       'Pack: 10 caps | Strength: 100mg',
       'Pack: 500ml | Form: Liquid | Strength: 25mg|5ml',
       'Pack: 100 caps | Strength: 25mg | Form: Capsule',
       'Pack: 30 tabs | Strength: 200mg | Form: Tablet',
       'Pack: 30 tabs | Strength: 50mg | Form: Tablet',
       'Strength: 250mg | Pack: 100 tabs | Form: Tablet',
       'Pack: 90 units',
       'Pack: 300ml | Strength: 25mg|5ml | Form: Liquid',
       'Pack: 100 units', 'Strength: 25mg | Pack: 20 tabs',
       'Pack: 10 caps | Strength: 500mg | Form: Capsule',
       'Form: Cream | Pack: 100g',
       'Pack: 500ml | Strength: 50mg|5ml | Form: Liquid',
       'Form: Tablet | Strength: 250mg | Pack: 90 tabs',
       'Pack: 90 caps | Strength: 200mg | Form: Capsule',
       'Pack: 100 tabs | Strength: 200mg | Form: Tablet',
       'Pack: 90 caps | Strength: 25mg | Form: Capsule',
       'Strength: 250mg | Form: Tablet | Pack: 30 tabs',
       'Pack: 100ml | Strength: 250mg|5ml | Form: Liquid',
       'Strength: 250mg | Form: Tablet | Pack: 90 tabs',
       'Form: Tablet | Strength: 100mg | Pack: 100 tabs',
       'Pack: 10 tabs | Strength: 250mg | Form: Tablet',
       'Pack: 90 tabs | Strength: 200mg | Form: Tablet',
       'Pack: 450ml | Strength: 650mg|5ml | Form: Liquid',
       'Pack: 50ml | Strength: 50mg|5ml | Form: Liquid',
       'Pack: 450ml | Strength: 50mg|5ml | Form: Liquid',
       'Pack: 10 tabs | Strength: 50mg | Form: Tablet',
       'Strength: 200mg | Pack: 20 tabs',
       'Pack: 20 tabs | Strength: 100mg | Form: Tablet',
       'Pack: 30 tabs | Strength: 100mg | Form: Tablet',
       'Pack: 100 tabs | Form: Tablet | Strength: 200mg',
       'Form: Capsule | Pack: 20 caps | Strength: 25mg',
       'Pack: 100 caps | Strength: 650mg | Form: Capsule',
       'Pack: 30 units', 'Strength: 100mg | Pack: 30 tabs',
       'Pack: 300ml | Strength: 250mg|5ml',
       'Pack: 30 caps | Strength: 650mg | Form: Capsule',
       'Pack: 30 caps | Form: Capsule | Strength: 250mg',
       'Pack: 100 caps | Strength: 500mg | Form: Capsule', 'Pack: 60g',
       'Pack: 50ml | Strength: 100mg|5ml | Form: Liquid',
       'Form: Cream | Pack: 10g', 'Strength: 200mg | Pack: 60 tabs',
       'Pack: 60 caps | Strength: 250mg | Form: Capsule',
       'Pack: 100 caps | Strength: 250mg | Form: Capsule', 'Pack: 90g',
       'Pack: 90 tabs | Strength: 650mg | Form: Tablet',
       'Pack: 100 caps | Strength: 200mg', 'Form: Kit | Pack: 60 units',
       'Pack: 100 tabs | Strength: 500mg | Form: Tablet',
       'Pack: 60 tabs | Strength: 50mg',
       'Pack: 90 caps | Strength: 200mg',
       'Pack: 450ml | Strength: 100mg|5ml | Form: Liquid',
       'Pack: 10 caps | Strength: 50mg | Form: Capsule',
       'Pack: 90 tabs | Strength: 100mg | Form: Tablet',
       'Form: Tablet | Strength: 25mg | Pack: 90 tabs',
       'Strength: 200mg|5ml | Pack: 150ml',
       'Form: Liquid | Strength: 650mg|5ml | Pack: 300ml',
       'Pack: 10 tabs | Strength: 200mg | Form: Tablet',
       'Pack: 20 tabs | Strength: 100mg',
       'Pack: 150ml | Strength: 25mg|5ml | Form: Liquid',
       'Pack: 10 caps | Strength: 250mg | Form: Capsule',
       'Pack: 300ml | Strength: 50mg|5ml | Form: Liquid',
       'Strength: 650mg | Form: Capsule | Pack: 30 caps',
       'Pack: 60 tabs | Strength: 50mg | Form: Tablet',
       'Strength: 250mg | Pack: 90 caps',
       'Pack: 100ml | Strength: 250mg|5ml',
       'Pack: 90 tabs | Strength: 500mg | Form: Tablet',
       'Pack: 20 caps | Strength: 100mg | Form: Capsule',
       'Strength: 500mg | Pack: 60 caps | Form: Capsule',
       'Pack: 90 caps | Strength: 650mg | Form: Capsule',
       'Pack: 100 caps | Strength: 25mg',
       'Pack: 50ml | Strength: 25mg|5ml | Form: Liquid',
       'Form: Bandage | Pack: 20g',
       'Pack: 450ml | Strength: 500mg|5ml | Form: Liquid',
       'Pack: 100 tabs | Strength: 250mg', 'Form: Kit | Pack: 100 units',
       'Pack: 60 caps | Strength: 25mg | Form: Capsule',
       'Pack: 50ml | Strength: 500mg|5ml | Form: Liquid',
       'Pack: 100ml | Strength: 500mg|5ml | Form: Liquid',
       'Form: Liquid | Strength: 25mg|5ml | Pack: 300ml',
       'Form: Tablet | Strength: 100mg | Pack: 10 tabs',
       'Pack: 100ml | Strength: 650mg|5ml | Form: Liquid',
       'Strength: 100mg | Form: Tablet | Pack: 60 tabs',
       'Pack: 90 caps | Strength: 250mg | Form: Capsule',
       'Strength: 650mg | Pack: 60 tabs',
       'Pack: 300ml | Strength: 200mg|5ml | Form: Liquid',
       'Strength: 250mg|5ml | Pack: 100ml',
       'Pack: 50ml | Strength: 200mg|5ml | Form: Liquid',
       'Pack: 100 caps | Strength: 50mg',
       'Strength: 100mg|5ml | Pack: 100ml',
       'Pack: 100 caps | Strength: 50mg | Form: Capsule',
       'Form: Kit | Pack: 20 units',
       'Pack: 100ml | Strength: 50mg|5ml | Form: Liquid',
       'Strength: 50mg | Pack: 100 caps | Form: Capsule',
       'Strength: 25mg|5ml | Pack: 500ml',
       'Pack: 50ml | Strength: 250mg|5ml',
       'Pack: 90 caps | Form: Capsule | Strength: 200mg',
       'Pack: 150ml | Strength: 650mg|5ml | Form: Liquid',
       'Strength: 25mg | Pack: 30 tabs',
       'Form: Tablet | Strength: 50mg | Pack: 100 tabs',
       'Pack: 20 tabs | Form: Tablet | Strength: 500mg',
       'Strength: 100mg|5ml | Pack: 50ml',
       'Pack: 90 caps | Strength: 50mg',
       'Pack: 60 caps | Strength: 500mg | Form: Capsule',
       'Pack: 20 tabs | Form: Tablet | Strength: 25mg',
       'Pack: 300ml | Strength: 650mg|5ml | Form: Liquid',
       'Pack: 90 tabs | Strength: 250mg | Form: Tablet',
       'Pack: 300ml | Strength: 500mg|5ml | Form: Liquid',
       'Pack: 20 caps | Strength: 500mg | Form: Capsule',
       'Pack: 100 caps | Strength: 250mg',
       'Pack: 10 tabs | Strength: 650mg | Form: Tablet',
       'Pack: 10 caps | Strength: 650mg | Form: Capsule',
       'Pack: 100ml | Strength: 25mg|5ml | Form: Liquid',
       'Pack: 10 tabs | Strength: 250mg',
       'Form: Tablet | Pack: 60 tabs | Strength: 50mg',
       'Strength: 500mg | Pack: 10 caps',
       'Pack: 500ml | Strength: 100mg|5ml | Form: Liquid',
       'Pack: 500ml | Strength: 25mg|5ml | Form: Liquid',
       'Pack: 150ml | Strength: 100mg|5ml | Form: Liquid',
       'Strength: 25mg | Pack: 10 tabs | Form: Tablet',
       'Pack: 90 tabs | Strength: 200mg',
       'Pack: 60 tabs | Strength: 25mg | Form: Tablet',
       'Strength: 100mg | Pack: 100 tabs',
       'Strength: 250mg | Pack: 10 tabs | Form: Tablet',
       'Strength: 200mg | Pack: 90 tabs | Form: Tablet',
       'Warranty: 24m | Form: Device',
       'Strength: 650mg|5ml | Pack: 150ml',
       'Strength: 200mg | Pack: 10 tabs',
       'Pack: 500ml | Strength: 200mg|5ml | Form: Liquid',
       'Pack: 450ml | Form: Liquid | Strength: 250mg|5ml',
       'Pack: 500ml | Strength: 250mg|5ml | Form: Liquid',
       'Pack: 60 tabs | Strength: 650mg | Form: Tablet',
       'Pack: 50ml | Strength: 250mg|5ml | Form: Liquid',
       'Form: Cream | Pack: 20g', 'Warranty: 12m | Form: Device',
       'Pack: 90 tabs | Form: Tablet | Strength: 500mg',
       'Pack: 100ml | Strength: 200mg|5ml | Form: Liquid',
       'Pack: 100 tabs | Strength: 25mg | Form: Tablet',
       'Form: Capsule | Pack: 30 caps | Strength: 50mg',
       'Pack: 30 tabs | Strength: 100mg',
       'Strength: 250mg|5ml | Form: Liquid | Pack: 100ml',
       'Strength: 650mg|5ml | Pack: 500ml',
       'Pack: 30 caps | Strength: 200mg | Form: Capsule',
       'Form: Tablet | Strength: 50mg | Pack: 20 tabs',
       'Pack: 300ml | Strength: 100mg|5ml | Form: Liquid',
       'Pack: 20 caps | Strength: 200mg | Form: Capsule',
       'Pack: 10 caps | Strength: 200mg | Form: Capsule',
       'Pack: 60 caps | Strength: 50mg | Form: Capsule',
       'Pack: 30 tabs | Strength: 650mg',
       'Pack: 150ml | Strength: 50mg|5ml',
       'Pack: 20 tabs | Strength: 500mg | Form: Tablet',
       'Strength: 25mg | Pack: 90 tabs',
       'Pack: 30 caps | Strength: 250mg | Form: Capsule',
       'Pack: 500ml | Strength: 500mg|5ml | Form: Liquid',
       'Pack: 10 tabs | Strength: 25mg | Form: Tablet', 'Pack: 10 units',
       'Pack: 20 caps | Strength: 25mg | Form: Capsule',
       'Strength: 200mg|5ml | Pack: 300ml',
       'Pack: 60 caps | Strength: 100mg | Form: Capsule',
       'Pack: 300ml | Strength: 100mg|5ml',
       'Pack: 20 caps | Strength: 500mg',
       'Pack: 60 tabs | Strength: 250mg | Form: Tablet',
       'Strength: 25mg | Form: Capsule | Pack: 10 caps',
       'Form: Kit | Pack: 10 units',
       'Form: Capsule | Pack: 60 caps | Strength: 500mg',
       'Strength: 50mg|5ml | Pack: 450ml | Form: Liquid',
       'Pack: 90 caps | Strength: 100mg | Form: Capsule',
       'Pack: 450ml | Form: Liquid | Strength: 50mg|5ml',
       'Strength: 500mg | Pack: 20 tabs',
       'Strength: 25mg | Pack: 30 caps | Form: Capsule',
       'Strength: 250mg|5ml | Pack: 300ml | Form: Liquid',
       'Strength: 50mg | Pack: 10 tabs',
       'Strength: 250mg | Pack: 10 tabs', 'Pack: 20 units',
       'Strength: 25mg | Pack: 60 tabs | Form: Tablet',
       'Pack: 20 caps | Strength: 50mg | Form: Capsule',
       'Strength: 50mg | Form: Tablet | Pack: 20 tabs',
       'Pack: 60 tabs | Strength: 200mg',
       'Pack: 90 caps | Strength: 50mg | Form: Capsule',
       'Strength: 25mg | Pack: 30 tabs | Form: Tablet',
       'Form: Bandage | Pack: 60g',
       'Form: Liquid | Strength: 100mg|5ml | Pack: 100ml',
       'Pack: 300ml | Strength: 200mg|5ml',
       'Pack: 20 tabs | Strength: 250mg',
       'Pack: 60 caps | Strength: 100mg',
       'Strength: 250mg | Form: Capsule | Pack: 20 caps',
       'Pack: 20 caps | Strength: 250mg | Form: Capsule',
       'Form: Bandage | Pack: 90g',
       'Form: Tablet | Strength: 25mg | Pack: 20 tabs',
       'Pack: 450ml | Strength: 50mg|5ml',
       'Strength: 100mg | Form: Capsule | Pack: 100 caps',
       'Strength: 250mg|5ml | Pack: 450ml',
       'Form: Liquid | Pack: 300ml | Strength: 500mg|5ml',
       'Strength: 500mg | Pack: 20 caps | Form: Capsule',
       'Strength: 50mg|5ml | Pack: 450ml',
       'Strength: 25mg | Pack: 100 tabs',
       'Pack: 60 caps | Strength: 650mg | Form: Capsule',
       'Pack: 450ml | Strength: 200mg|5ml | Form: Liquid',
       'Form: Tablet | Pack: 90 tabs | Strength: 500mg',
       'Strength: 50mg | Form: Tablet | Pack: 10 tabs',
       'Strength: 100mg | Form: Tablet | Pack: 90 tabs',
       'Form: Tablet | Pack: 100 tabs | Strength: 250mg',
       'Pack: 50ml | Strength: 650mg|5ml | Form: Liquid',
       'Strength: 650mg | Pack: 90 caps | Form: Capsule',
       'Pack: 30 tabs | Strength: 250mg',
       'Pack: 30 caps | Strength: 50mg | Form: Capsule',
       'Form: Capsule | Pack: 90 caps | Strength: 100mg',
       'Form: Kit | Pack: 90 units', 'Strength: 100mg | Pack: 60 tabs',
       'Pack: 90 tabs | Strength: 100mg',
       'Pack: 90 tabs | Form: Tablet | Strength: 250mg',
       'Pack: 90 caps | Strength: 500mg',
       'Pack: 150ml | Strength: 250mg|5ml',
       'Pack: 30 tabs | Form: Tablet | Strength: 200mg',
       'Pack: 60 tabs | Form: Tablet | Strength: 500mg',
       'Pack: 50ml | Strength: 500mg|5ml',
       'Pack: 10 tabs | Strength: 200mg',
       'Pack: 450ml | Strength: 250mg|5ml | Form: Liquid',
       'Pack: 10 caps | Strength: 25mg',
       'Form: Capsule | Pack: 10 caps | Strength: 200mg',
       'Pack: 450ml | Strength: 25mg|5ml',
       'Pack: 90 tabs | Strength: 50mg', 'Form: Bandage | Pack: 30g',
       'Form: Tablet | Pack: 30 tabs | Strength: 500mg',
       'Pack: 500ml | Form: Liquid | Strength: 100mg|5ml',
       'Strength: 650mg | Form: Tablet | Pack: 100 tabs',
       'Strength: 200mg | Pack: 90 tabs',
       'Pack: 100 tabs | Strength: 100mg',
       'Form: Tablet | Strength: 200mg | Pack: 100 tabs',
       'Pack: 150ml | Strength: 250mg|5ml | Form: Liquid',
       'Form: Tablet | Pack: 10 tabs | Strength: 50mg',
       'Form: Tablet | Strength: 500mg | Pack: 90 tabs',
       'Pack: 100 caps | Strength: 100mg | Form: Capsule',
       'Strength: 650mg|5ml | Form: Liquid | Pack: 100ml',
       'Pack: 90 caps | Form: Capsule | Strength: 100mg',
       'Strength: 50mg | Pack: 100 tabs',
       'Form: Liquid | Pack: 50ml | Strength: 25mg|5ml',
       'Form: Tablet | Pack: 20 tabs | Strength: 100mg',
       'Pack: 100 caps | Strength: 500mg',
       'Form: Liquid | Strength: 250mg|5ml | Pack: 500ml',
       'Pack: 30 tabs | Form: Tablet | Strength: 100mg',
       'Pack: 30 caps | Strength: 50mg',
       'Strength: 250mg | Pack: 90 tabs',
       'Pack: 300ml | Strength: 25mg|5ml',
       'Pack: 20 tabs | Strength: 25mg', 'Pack: 60 caps | Strength: 50mg',
       'Pack: 150ml | Strength: 500mg|5ml | Form: Liquid',
       'Pack: 60 tabs | Strength: 25mg',
       'Form: Liquid | Pack: 300ml | Strength: 650mg|5ml',
       'Pack: 20 caps | Strength: 650mg',
       'Pack: 10 caps | Strength: 100mg | Form: Capsule',
       'Strength: 250mg|5ml | Pack: 150ml',
       'Form: Tablet | Pack: 20 tabs | Strength: 500mg',
       'Pack: 50ml | Strength: 650mg|5ml',
       'Strength: 650mg | Pack: 20 tabs',
       'Pack: 450ml | Strength: 100mg|5ml',
       'Pack: 500ml | Strength: 200mg|5ml',
       'Form: Tablet | Pack: 10 tabs | Strength: 250mg',
       'Form: Capsule | Strength: 100mg | Pack: 90 caps',
       'Strength: 100mg | Pack: 10 tabs',
       'Strength: 500mg|5ml | Pack: 500ml',
       'Form: Liquid | Pack: 500ml | Strength: 250mg|5ml',
       'Pack: 30 caps | Form: Capsule | Strength: 500mg',
       'Pack: 60 tabs | Strength: 100mg',
       'Pack: 100 tabs | Strength: 50mg',
       'Strength: 200mg | Pack: 30 caps | Form: Capsule',
       'Strength: 500mg|5ml | Pack: 450ml',
       'Pack: 150ml | Strength: 650mg|5ml',
       'Form: Tablet | Strength: 650mg | Pack: 90 tabs',
       'Strength: 200mg|5ml | Pack: 50ml | Form: Liquid',
       'Strength: 25mg|5ml | Pack: 300ml',
       'Strength: 250mg | Pack: 20 tabs | Form: Tablet',
       'Pack: 10 caps | Strength: 50mg',
       'Strength: 500mg | Form: Tablet | Pack: 20 tabs',
       'Pack: 90 tabs | Strength: 25mg',
       'Form: Tablet | Strength: 250mg | Pack: 30 tabs',
       'Form: Tablet | Strength: 650mg | Pack: 10 tabs',
       'Form: Tablet | Pack: 100 tabs | Strength: 50mg',
       'Pack: 10 caps | Form: Capsule | Strength: 100mg',
       'Strength: 250mg | Pack: 100 tabs', 'Form: Bandage | Pack: 100g',
       'Pack: 90 tabs | Strength: 250mg',
       'Strength: 650mg | Pack: 90 tabs',
       'Strength: 250mg | Pack: 60 caps | Form: Capsule',
       'Pack: 500ml | Strength: 250mg|5ml',
       'Form: Liquid | Strength: 500mg|5ml | Pack: 150ml',
       'Strength: 200mg | Form: Tablet | Pack: 10 tabs',
       'Strength: 200mg | Form: Tablet | Pack: 30 tabs',
       'Form: Tablet | Pack: 90 tabs | Strength: 250mg',
       'Strength: 650mg | Form: Tablet | Pack: 90 tabs',
       'Form: Capsule | Pack: 30 caps | Strength: 500mg',
       'Form: Tablet | Strength: 500mg | Pack: 20 tabs',
       'Pack: 60 tabs | Strength: 500mg',
       'Strength: 100mg | Pack: 60 caps | Form: Capsule',
       'Strength: 50mg | Pack: 60 caps | Form: Capsule',
       'Pack: 90 tabs | Strength: 500mg',
       'Strength: 500mg | Form: Capsule | Pack: 30 caps',
       'Strength: 250mg | Pack: 30 tabs | Form: Tablet',
       'Strength: 50mg | Pack: 20 tabs',
       'Strength: 500mg | Pack: 60 tabs',
       'Strength: 50mg | Pack: 90 caps',
       'Strength: 250mg | Pack: 20 caps',
       'Strength: 50mg | Pack: 60 tabs',
       'Pack: 100 tabs | Form: Tablet | Strength: 250mg',
       'Form: Kit | Pack: 30 units',
       'Form: Tablet | Pack: 30 tabs | Strength: 200mg',
       'Pack: 50ml | Strength: 25mg|5ml',
       'Form: Liquid | Pack: 450ml | Strength: 250mg|5ml',
       'Strength: 100mg | Pack: 90 tabs',
       'Strength: 100mg | Pack: 20 tabs',
       'Pack: 60 caps | Form: Capsule | Strength: 200mg',
       'Strength: 200mg | Pack: 100 caps',
       'Strength: 50mg | Pack: 90 tabs | Form: Tablet',
       'Pack: 500ml | Strength: 650mg|5ml',
       'Strength: 100mg | Form: Tablet | Pack: 20 tabs',
       'Strength: 25mg | Form: Capsule | Pack: 60 caps',
       'Strength: 25mg | Form: Capsule | Pack: 90 caps',
       'Strength: 250mg | Pack: 30 caps',

In [33]:
def extract_pack_info(pack_info):
    
    if pd.isnull(pack_info) or str(pack_info).strip() == "":
        return pd.Series({'Pack Size': None, 'Strength': None, 'Form': None})
    
    pack_info_str = str(pack_info)

    pack_size_match = re.search(r'Pack:\s*([^|]+)', pack_info_str)
    strength_match = re.search(r'Strength:\s*([^|]+)', pack_info_str)
    form_match = re.search(r'Form:\s*([^|]+)', pack_info_str)

    return pd.Series({
        'Pack Size': pack_size_match.group(1).strip() if pack_size_match else None,
        'Strength': strength_match.group(1).strip() if strength_match else None,
        'Form': form_match.group(1).strip() if form_match else None
    })


extracted_pack_info = products_data['Pack Info'].apply(extract_pack_info)
products_data = pd.concat([products_data, extracted_pack_info], axis=1)

In [34]:
products_data['Form'].value_counts(dropna=False)

Form
None       913
Tablet     896
Cream      888
Kit        502
Device     500
Capsule    447
Bandage    428
Liquid     426
Name: count, dtype: int64

In [35]:
products_data.drop(columns=['Pack Info'], inplace=True)

In [36]:
products_data = products_data.merge(
    category_data[['Category Id', 'Category Name']], 
    on='Category Id', 
    how='left'
)

In [37]:
products_data

,Product Id,Product Name,Category Id,Supplier Id,Unit Price,Cost Price,Brand,Expiry Date,Storage Condition,Created At,Pack Size,Strength,Form,Category Name
0,2,Health Product 2,8,3,111.42,64.75,MediCare,8/8/2026,Refrigerated,9/13/2022,None,None,None,Skin & Derma Care
1,39,Health Product 39,9,5,34.55,21.04,BioZen,12/29/2025,Refrigerated,8/6/2025,None,None,None,Diagnostics
2,51,Health Product 51,3,2,146.82,89.56,CuraMax,9/17/2026,Refrigerated,9/7/2025,None,None,None,Vitamins & Supplements
3,76,Health Product 76,1,3,154.35,60.18,LifeLine,8/23/2026,Refrigerated,9/3/2024,None,None,None,Prescription Drugs
4,123,Health Product 123,8,4,299.65,174.20,CuraMax,11/12/2028,Refrigerated,10/31/2025,None,None,None,Skin & Derma Care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4944,Health Product 4944,2,2,57.99,23.14,BioZen,9/8/2029,Ambient,8/1/2025,100 tabs,100mg,Tablet,OTC Pain Relief
4996,4946,Health Product 4946,1,2,294.70,176.63,CuraMax,11/27/2029,Ambient,8/8/2023,90 tabs,250mg,Tablet,Prescription Drugs
4997,4959,Health Product 4959,4,2,279.36,175.88,HealthPlus,11/2/2029,Ambient,10/25/2025,20g,None,Cream,Personal Care
4998,4963,Health Product 4963,7,2,83.39,48.87,HealthPlus,2/24/2029,Ambient,1/14/2025,10g,None,Bandage,First Aid
4999,4974,Health Product 4974,5,2,250.09,116.78,LifeLine,7/19/2027,Ambient,3/16/2025,None,None,Device,Medical Devices

##### 5) Stock Condition Table

In [38]:
stock_data.head(10)

,Stock Id,Store Id,Product Id,Quantity,Reorder Level,last Restocked,Batch Number,Expiry Date,Received Date,Condition Notes
0,37,10,2214,28,31,2/23/2026,BATCH-37,1/9/2030,2/23/2026,NaN
1,61,10,755,114,48,9/11/2025,BATCH-61,2/6/2029,9/11/2025,NaN
2,109,10,4892,59,24,12/3/2025,BATCH-109,8/10/2028,12/3/2025,NaN
3,132,10,373,10,35,8/25/2025,BATCH-132,8/1/2028,8/25/2025,NaN
4,137,10,33,90,15,8/15/2026,BATCH-137,11/1/2027,8/15/2026,NaN
5,187,10,554,27,20,6/18/2026,BATCH-187,3/12/2028,6/18/2026,NaN
6,194,10,4389,93,41,3/23/2026,BATCH-194,5/15/2028,3/23/2026,NaN
7,205,10,4531,98,17,1/4/2026,BATCH-205,3/26/2028,1/4/2026,NaN
8,212,10,4379,42,33,11/27/2025,BATCH-212,11/28/2026,11/27/2025,NaN
9,269,10,3684,103,59,3/22/2026,BATCH-269,3/10/2029,3/22/2026,NaN

In [39]:
stock_data['Condition Notes'].unique()

array([nan, 'Expiring in 0 days - flag for clearance',
       'Expiring in 11 days - flag for clearance',
       'Expiring in 17 days - flag for clearance',
       'Below reorder level - reorder placed 2025-11-10',
       'Below reorder level - reorder placed 2025-10-30',
       'Below reorder level - reorder placed 2026-04-11',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-12-08',
       'Below reorder level - reorder placed 2025-12-24',
       'Below reorder level - reorder placed 2026-06-22',
       'Expiring in 45 days - monitor; Below reorder level - reorder placed 2026-04-27',
       'Below reorder level - reorder placed 2026-09-03',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-07-21',
       'Below reorder level - reorder placed 2025-10-05',
       'Below reorder level - reorder placed 2026-07-08',
       'Below reorder level - reorder placed 2026-07-27',
       'Below reorder level - reorder placed 2026-01-24',
       'Expiring in 27 days - flag for clearance',
       'Below reorder level - reorder placed 2025-07-20',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-07-14',
       'Expiring in 48 days - monitor',
       'Below reorder level - reorder placed 2025-07-21',
       'Below reorder level - reorder placed 2026-05-07',
       'Expiring in 32 days - monitor',
       'Below reorder level - reorder placed 2026-03-11',
       'Below reorder level - reorder placed 2025-07-11',
       'Below reorder level - reorder placed 2026-03-18',
       'Below reorder level - reorder placed 2026-01-19',
       'Expiring in 74 days - monitor',
       'Expiring in 22 days - flag for clearance',
       'Below reorder level - reorder placed 2026-01-01',
       'Below reorder level - reorder placed 2025-09-18',
       'Below reorder level - reorder placed 2026-08-21',
       'Below reorder level - reorder placed 2026-03-08',
       'Expiring in 29 days - flag for clearance; Below reorder level - reorder placed 2025-08-15',
       'Below reorder level - reorder placed 2026-02-11',
       'Below reorder level - reorder placed 2026-01-18',
       'Below reorder level - reorder placed 2025-06-18',
       'Below reorder level - reorder placed 2026-06-23',
       'Expiring in 43 days - monitor',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-11-24',
       'Below reorder level - reorder placed 2026-06-08',
       'Expiring in 76 days - monitor', 'Expiring in 46 days - monitor',
       'Below reorder level - reorder placed 2026-01-23',
       'Expiring in 9 days - flag for clearance',
       'Below reorder level - reorder placed 2025-06-17',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-07-05',
       'Below reorder level - reorder placed 2025-12-18',
       'Expiring in 8 days - flag for clearance',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-08-30',
       'Below reorder level - reorder placed 2026-07-31',
       'Expiring in 7 days - flag for clearance',
       'Below reorder level - reorder placed 2026-06-30',
       'Below reorder level - reorder placed 2026-03-13',
       'Below reorder level - reorder placed 2026-08-08',
       'Below reorder level - reorder placed 2025-12-22',
       'Below reorder level - reorder placed 2025-07-08',
       'Below reorder level - reorder placed 2026-07-30',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-01-09',
       'Expiring in 12 days - flag for clearance; Below reorder level - reorder placed 2026-03-21',
       'Below reorder level - reorder placed 2026-04-04',
       'Expiring in 45 days - monitor',
       'Below reorder level - reorder placed 2025-06-27',
       'Below reorder level - reorder placed 2025-09-17',
       'Expiring in 51 days - monitor',
       'Below reorder level - reorder placed 2026-08-27',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-11-17',
       'Below reorder level - reorder placed 2025-07-29',
       'Expiring in 14 days - flag for clearance; Below reorder level - reorder placed 2026-05-12',
       'Below reorder level - reorder placed 2025-07-04',
       'Below reorder level - reorder placed 2025-12-11',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-04-14',
       'Expiring in 28 days - flag for clearance',
       'Below reorder level - reorder placed 2025-12-20',
       'Below reorder level - reorder placed 2025-07-07',
       'Below reorder level - reorder placed 2025-12-19',
       'Expiring in 86 days - monitor',
       'Below reorder level - reorder placed 2025-11-27',
       'Below reorder level - reorder placed 2025-10-03',
       'Below reorder level - reorder placed 2025-12-17',
       'Below reorder level - reorder placed 2026-04-06',
       'Expiring in 69 days - monitor',
       'Below reorder level - reorder placed 2025-11-03',
       'Below reorder level - reorder placed 2026-06-20',
       'Expiring in 6 days - flag for clearance',
       'Below reorder level - reorder placed 2025-07-19',
       'Below reorder level - reorder placed 2025-12-25',
       'Below reorder level - reorder placed 2026-02-04',
       'Expiring in 34 days - monitor',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-12-21',
       'Below reorder level - reorder placed 2026-03-27',
       'Expiring in 29 days - flag for clearance',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-05-25',
       'Below reorder level - reorder placed 2026-01-15',
       'Below reorder level - reorder placed 2026-03-20',
       'Below reorder level - reorder placed 2026-04-19',
       'Below reorder level - reorder placed 2025-08-24',
       'Below reorder level - reorder placed 2026-07-12',
       'Below reorder level - reorder placed 2025-08-12',
       'Below reorder level - reorder placed 2026-04-01',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-09-09',
       'Below reorder level - reorder placed 2026-08-31',
       'Below reorder level - reorder placed 2026-03-24',
       'Below reorder level - reorder placed 2025-11-22',
       'Below reorder level - reorder placed 2026-06-28',
       'Below reorder level - reorder placed 2025-12-23',
       'Below reorder level - reorder placed 2026-05-22',
       'Expiring in 23 days - flag for clearance',
       'Below reorder level - reorder placed 2025-07-17',
       'Expiring in 5 days - flag for clearance',
       'Below reorder level - reorder placed 2026-06-21',
       'Below reorder level - reorder placed 2026-04-29',
       'Below reorder level - reorder placed 2025-11-26',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-09-05',
       'Expiring in 70 days - monitor',
       'Expiring in 15 days - flag for clearance',
       'Below reorder level - reorder placed 2026-05-19',
       'Expiring in 14 days - flag for clearance',
       'Expiring in 21 days - flag for clearance; Below reorder level - reorder placed 2026-01-21',
       'Below reorder level - reorder placed 2026-04-23',
       'Below reorder level - reorder placed 2026-01-16',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-07-08',
       'Below reorder level - reorder placed 2025-06-24',
       'Expiring in 24 days - flag for clearance; Below reorder level - reorder placed 2026-06-02',
       'Below reorder level - reorder placed 2026-02-16',
       'Below reorder level - reorder placed 2026-03-05',
       'Below reorder level - reorder placed 2026-03-12',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-08-29',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-09-10',
       'Below reorder level - reorder placed 2025-09-19',
       'Below reorder level - reorder placed 2026-05-04',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-12-15',
       'Below reorder level - reorder placed 2025-12-06',
       'Below reorder level - reorder placed 2025-12-21',
       'Expiring in 24 days - flag for clearance',
       'Expiring in 55 days - monitor', 'Expiring in 35 days - monitor',
       'Below reorder level - reorder placed 2025-06-15',
       'Below reorder level - reorder placed 2025-09-28',
       'Below reorder level - reorder placed 2025-06-29',
       'Expiring in 13 days - flag for clearance; Below reorder level - reorder placed 2025-09-17',
       'Below reorder level - reorder placed 2025-10-15',
       'Expiring in 13 days - flag for clearance',
       'Expiring in 23 days - flag for clearance; Below reorder level - reorder placed 2025-08-04',
       'Below reorder level - reorder placed 2025-10-14',
       'Below reorder level - reorder placed 2026-09-05',
       'Below reorder level - reorder placed 2026-06-01',
       'Expiring in 10 days - flag for clearance',
       'Below reorder level - reorder placed 2026-06-06',
       'Below reorder level - reorder placed 2026-01-13',
       'Expiring in 20 days - flag for clearance',
       'Below reorder level - reorder placed 2025-08-31',
       'Below reorder level - reorder placed 2026-07-23',
       'Below reorder level - reorder placed 2025-11-21',
       'Below reorder level - reorder placed 2026-09-06',
       'Expiring in 6 days - flag for clearance; Below reorder level - reorder placed 2025-06-26',
       'Below reorder level - reorder placed 2026-05-01',
       'Expiring in 1 days - flag for clearance',
       'Below reorder level - reorder placed 2026-01-03',
       'Below reorder level - reorder placed 2025-06-10',
       'Below reorder level - reorder placed 2026-02-26',
       'Below reorder level - reorder placed 2026-01-17',
       'Expiring in 65 days - monitor',
       'Below reorder level - reorder placed 2025-09-02',
       'Below reorder level - reorder placed 2026-05-11',
       'Below reorder level - reorder placed 2026-07-29',
       'Expiring in 68 days - monitor',
       'Below reorder level - reorder placed 2026-02-15',
       'Below reorder level - reorder placed 2026-06-12',
       'Below reorder level - reorder placed 2025-08-06',
       'Expiring in 44 days - monitor; Below reorder level - reorder placed 2026-04-25',
       'Expiring in 67 days - monitor',
       'Below reorder level - reorder placed 2025-09-24',
       'Expiring in 24 days - flag for clearance; Below reorder level - reorder placed 2026-04-01',
       'Below reorder level - reorder placed 2025-10-22',
       'Below reorder level - reorder placed 2025-10-25',
       'Below reorder level - reorder placed 2026-05-10',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-07-07',
       'Expiring in 3 days - flag for clearance',
       'Below reorder level - reorder placed 2026-04-05',
       'Below reorder level - reorder placed 2026-08-12',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-01-03',
       'Expiring in 28 days - flag for clearance; Below reorder level - reorder placed 2026-04-17',
       'Below reorder level - reorder placed 2025-12-13',
       'Expiring in 12 days - flag for clearance',
       'Below reorder level - reorder placed 2025-10-12',
       'Below reorder level - reorder placed 2025-11-30',
       'Below reorder level - reorder placed 2025-09-30',
       'Below reorder level - reorder placed 2025-08-28',
       'Below reorder level - reorder placed 2026-06-07',
       'Expiring in 41 days - monitor',
       'Expiring in 6 days - flag for clearance; Below reorder level - reorder placed 2026-06-12',
       'Expiring in 66 days - monitor',
       'Below reorder level - reorder placed 2025-09-06',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-11-04',
       'Below reorder level - reorder placed 2026-08-07',
       'Expiring in 5 days - flag for clearance; Below reorder level - reorder placed 2026-06-02',
       'Below reorder level - reorder placed 2026-02-03',
       'Expiring in 16 days - flag for clearance',
       'Below reorder level - reorder placed 2026-07-17',
       'Expiring in 59 days - monitor', 'Expiring in 49 days - monitor',
       'Below reorder level - reorder placed 2026-07-15',
       'Below reorder level - reorder placed 2026-08-24',
       'Below reorder level - reorder placed 2025-12-16',
       'Below reorder level - reorder placed 2025-07-12',
       'Below reorder level - reorder placed 2026-04-25',
       'Expiring in 4 days - flag for clearance',
       'Below reorder level - reorder placed 2026-03-26',
       'Below reorder level - reorder placed 2025-06-22',
       'Expiring in 29 days - flag for clearance; Below reorder level - reorder placed 2025-06-21',
       'Below reorder level - reorder placed 2026-07-26',
       'Below reorder level - reorder placed 2025-06-20',
       'Below reorder level - reorder placed 2025-11-02',
       'Below reorder level - reorder placed 2026-05-24',
       'Below reorder level - reorder placed 2026-01-09',
       'Expiring in 26 days - flag for clearance; Below reorder level - reorder placed 2025-11-02',
       'Below reorder level - reorder placed 2026-06-24',
       'Below reorder level - reorder placed 2025-07-10',
       'Below reorder level - reorder placed 2025-10-26',
       'Below reorder level - reorder placed 2026-07-09',
       'Below reorder level - reorder placed 2026-03-22',
       'Expiring in 19 days - flag for clearance; Below reorder level - reorder placed 2025-10-04',
       'Below reorder level - reorder placed 2025-08-09',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-05-05',
       'Expiring in 56 days - monitor; Below reorder level - reorder placed 2025-10-17',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-07-07',
       'Expiring in 79 days - monitor',
       'Below reorder level - reorder placed 2026-05-30',
       'Expiring in 78 days - monitor',
       'Below reorder level - reorder placed 2025-08-11',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-07-19',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-04-26',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-09-02',
       'Below reorder level - reorder placed 2026-05-15',
       'Below reorder level - reorder placed 2025-08-17',
       'Expiring in 58 days - monitor',
       'Below reorder level - reorder placed 2025-08-04',
       'Below reorder level - reorder placed 2025-08-02',
       'Below reorder level - reorder placed 2025-08-19',
       'Below reorder level - reorder placed 2025-07-28',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-09-06',
       'Expiring in 75 days - monitor',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-02-04',
       'Below reorder level - reorder placed 2025-07-25',
       'Below reorder level - reorder placed 2026-08-03',
       'Expiring in 18 days - flag for clearance',
       'Below reorder level - reorder placed 2025-11-12',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-10-25',
       'Below reorder level - reorder placed 2026-07-03',
       'Below reorder level - reorder placed 2025-07-16',
       'Below reorder level - reorder placed 2026-05-21',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-07-28',
       'Below reorder level - reorder placed 2025-12-15',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-09-06',
       'Below reorder level - reorder placed 2026-08-18',
       'Below reorder level - reorder placed 2025-09-03',
       'Below reorder level - reorder placed 2025-11-19',
       'Below reorder level - reorder placed 2026-05-18',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-02-13',
       'Below reorder level - reorder placed 2026-01-04',
       'Below reorder level - reorder placed 2026-05-26',
       'Below reorder level - reorder placed 2025-06-25',
       'Below reorder level - reorder placed 2026-03-23',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-10-19',
       'Below reorder level - reorder placed 2026-09-11',
       'Below reorder level - reorder placed 2026-08-10',
       'Below reorder level - reorder placed 2025-10-28',
       'Below reorder level - reorder placed 2025-09-16',
       'Below reorder level - reorder placed 2025-09-26',
       'Below reorder level - reorder placed 2026-03-31',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-03-29',
       'Below reorder level - reorder placed 2025-12-31',
       'Expiring in 71 days - monitor',
       'Below reorder level - reorder placed 2026-04-24',
       'Below reorder level - reorder placed 2025-10-07',
       'Below reorder level - reorder placed 2026-02-24',
       'Below reorder level - reorder placed 2026-04-26',
       'Below reorder level - reorder placed 2025-09-14',
       'Expiring in 78 days - monitor; Below reorder level - reorder placed 2025-08-12',
       'Below reorder level - reorder placed 2026-06-15',
       'Below reorder level - reorder placed 2025-12-27',
       'Below reorder level - reorder placed 2026-08-26',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-09-20',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-06-27',
       'Expiring in 16 days - flag for clearance; Below reorder level - reorder placed 2025-10-22',
       'Expiring in 56 days - monitor',
       'Below reorder level - reorder placed 2026-02-17',
       'Below reorder level - reorder placed 2025-08-27',
       'Below reorder level - reorder placed 2025-10-06',
       'Below reorder level - reorder placed 2026-02-01',
       'Below reorder level - reorder placed 2026-07-25',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-04-27',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-08-22',
       'Below reorder level - reorder placed 2025-07-30',
       'Below reorder level - reorder placed 2025-11-28',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-03-12',
       'Expiring in 54 days - monitor',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-07-12',
       'Below reorder level - reorder placed 2025-06-16',
       'Below reorder level - reorder placed 2026-08-25',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2025-10-18',
       'Below reorder level - reorder placed 2026-09-08',
       'Below reorder level - reorder placed 2025-11-08',
       'Below reorder level - reorder placed 2026-09-04',
       'Below reorder level - reorder placed 2025-12-28',
       'Expiring in 23 days - flag for clearance; Below reorder level - reorder placed 2026-07-23',
       'Expiring in 0 days - flag for clearance; Below reorder level - reorder placed 2026-03-11',
       'Below reorder level - reorder placed 2026-07-06',
       'Below reorder level - reorder placed 2026-02-25',
       'Below reorder level - reorder placed 2025-10-17',
       'Below reorder level - reorder placed 2026-09-02',
       'Below reorder level - reorder placed 2025-07-14',

In [40]:
# Extracting information from the 'Condition Notes' column
def extract_condition(note):
    if pd.isnull(note) or note.strip() == "":
        return pd.Series({'Expiry Risk Flag':False, 'Days To Expiry Flagged':None,'Below Recorder Flag':False,'Recorder Placed Date':None})

    expiry_match=re.search(r'Expiring in (\d+) days', note)
    recorder_match=re.search(r'Below reorder level - reorder placed (\d{4}-\d{2}-\d{2})', note)  

    return pd.Series({'Expiry Risk Flag':bool(expiry_match),
                      'Days To Expiry Flagged':int(expiry_match.group(1)) if expiry_match else None,
                      'Below Recorder Flag':bool(recorder_match),
                      'Recorder Placed Date':recorder_match.group(1) if recorder_match else None})

extracted_condition=stock_data['Condition Notes'].apply(extract_condition)
stock_data=pd.concat([stock_data,extracted_condition],axis=1)

In [41]:
stock_data.drop(columns=['Condition Notes'],inplace=True)

In [42]:
stock_data.head(10)

,Stock Id,Store Id,Product Id,Quantity,Reorder Level,last Restocked,Batch Number,Expiry Date,Received Date,Expiry Risk Flag,Days To Expiry Flagged,Below Recorder Flag,Recorder Placed Date
0,37,10,2214,28,31,2/23/2026,BATCH-37,1/9/2030,2/23/2026,False,NaN,False,None
1,61,10,755,114,48,9/11/2025,BATCH-61,2/6/2029,9/11/2025,False,NaN,False,None
2,109,10,4892,59,24,12/3/2025,BATCH-109,8/10/2028,12/3/2025,False,NaN,False,None
3,132,10,373,10,35,8/25/2025,BATCH-132,8/1/2028,8/25/2025,False,NaN,False,None
4,137,10,33,90,15,8/15/2026,BATCH-137,11/1/2027,8/15/2026,False,NaN,False,None
5,187,10,554,27,20,6/18/2026,BATCH-187,3/12/2028,6/18/2026,False,NaN,False,None
6,194,10,4389,93,41,3/23/2026,BATCH-194,5/15/2028,3/23/2026,False,NaN,False,None
7,205,10,4531,98,17,1/4/2026,BATCH-205,3/26/2028,1/4/2026,False,NaN,False,None
8,212,10,4379,42,33,11/27/2025,BATCH-212,11/28/2026,11/27/2025,False,NaN,False,None
9,269,10,3684,103,59,3/22/2026,BATCH-269,3/10/2029,3/22/2026,False,NaN,False,None

In [43]:
sales_data.columns

Index(['Sale Id', 'Store Id', 'Employee Id', 'Product Id', 'Customer Id',
       'Quantity', 'Sale Date', 'Unit Price', 'Discount Pct', 'Payment Method',
       'Promo Code', 'Discount Reason'],
      dtype='object')

#### Feature Engineering

In [44]:
sales_data['Total Amount']=(sales_data['Quantity'] * sales_data['Unit Price'] * (1 - sales_data['Discount Pct']/100)).round(2)

In [45]:
sales_data=sales_data.merge(products_data[['Product Id', 'Cost Price']])

In [46]:
sales_data['Cost Amount']=(sales_data['Quantity'] * sales_data['Cost Price']).round(2)

In [47]:
sales_data['Profit']=(sales_data['Total Amount'] - sales_data['Cost Amount']).round(2)

In [48]:
sales_data['Profit Margin Pct']=(sales_data['Profit']/sales_data['Total Amount']*100).round(2)

#### Data Validation

###### 1) Null Validation

In [49]:
def null_validation(data,table_name):
    nulls=data.isnull().sum()
    nulls=nulls[nulls>0]

    if len(nulls)==0:
        print(f'{table_name} : No Null values')
    else:
        print(f'{table_name} : Null values found')

In [50]:
null_validation(customer_data,'CustomerMaster')
null_validation(sales_data,'AllSales')
null_validation(category_data,'Categories')
null_validation(employees_data,'Employees')
null_validation(prescriptions_data,'Prescriptions')
null_validation(products_data,'ProductCatalog')
null_validation(stock_data,'Stock')
null_validation(stores_data,'Stores')
null_validation(suppliers_data,'Suppliers')

CustomerMaster : Null values found
AllSales : Null values found
Categories : No Null values
Employees : No Null values
Prescriptions : No Null values
ProductCatalog : Null values found
Stock : Null values found
Stores : No Null values
Suppliers : No Null values

###### 2) Duplicates Validation

In [51]:
def duplicates_validation(data,table_name):
    duplicates=data.duplicated().sum()

    if duplicates==0:
        print(f'{table_name} : No duplicates')
    else:
        print(f'{table_name} : Duplicated found')

In [52]:
duplicates_validation(customer_data,'CustomerMaster')
duplicates_validation(sales_data,'AllSales')
duplicates_validation(category_data,'Categories')
duplicates_validation(employees_data,'Employees')
duplicates_validation(prescriptions_data,'Prescriptions')
duplicates_validation(products_data,'ProductCatalog')
duplicates_validation(stock_data,'Stock')
duplicates_validation(stores_data,'Stores')
duplicates_validation(suppliers_data,'Suppliers')

CustomerMaster : No duplicates
AllSales : No duplicates
Categories : No duplicates
Employees : No duplicates
Prescriptions : No duplicates
ProductCatalog : No duplicates
Stock : No duplicates
Stores : No duplicates
Suppliers : No duplicates

###### 3) Data Types Validation

In [53]:
def data_types_validation(data,table_name):
    print(f'\n-----{table_name}-----')
    print(data.dtypes)

In [54]:
data_types_validation(customer_data,'CustomerMaster')
data_types_validation(sales_data,'AllSales')
data_types_validation(category_data,'Categories')
data_types_validation(employees_data,'Employees')
data_types_validation(prescriptions_data,'Prescriptions')
data_types_validation(products_data,'ProductCatalog')
data_types_validation(stock_data,'Stock')
data_types_validation(stores_data,'Stores')
data_types_validation(suppliers_data,'Suppliers')

-----CustomerMaster-----
Customer Id        int64
Full Name         object
Email             object
Phone             object
City              object
Signup Date       object
Loyalty Tier      object
Loyalty Since    float64
City Clean        object
Phone Clean       object
dtype: object

-----AllSales-----
Sale Id                int64
Store Id               int64
Employee Id            int64
Product Id             int64
Customer Id            int64
Quantity               int64
Sale Date             object
Unit Price           float64
Discount Pct         float64
Payment Method        object
Promo Code            object
Discount Reason       object
Total Amount         float64
Cost Price           float64
Cost Amount          float64
Profit               float64
Profit Margin Pct    float64
dtype: object

-----Categories-----
Category Id       int64
Category Name    object
dtype: object

-----Employees-----
Employee Id        int64
Store Id           int64
Employee Name     object
Email             object
Position          object
Salary           float64
Hire Date         object
Is Pharmacist      int32
dtype: object

-----Prescriptions-----
Prescription Id     int64
Store Id            int64
Product Id          int64
Customer Id         int64
Doctor Name        object
Issue Date         object
Dosage             object
dtype: object

-----ProductCatalog-----
Product Id             int64
Product Name          object
Category Id            int64
Supplier Id            int64
Unit Price           float64
Cost Price           float64
Brand                 object
Expiry Date           object
Storage Condition     object
Created At            object
Pack Size             object
Strength              object
Form                  object
Category Name         object
dtype: object

-----Stock-----
Stock Id                    int64
Store Id                    int64
Product Id                  int64
Quantity                    int64
Reorder Level               int64
last Restocked             object
Batch Number               object
Expiry Date                object
Received Date              object
Expiry Risk Flag             bool
Days To Expiry Flagged    float64
Below Recorder Flag          bool
Recorder Placed Date       object
dtype: object

-----Stores-----
Store Id         int64
Store Name      object
Region          object
City            object
Manager Name    object
dtype: object

-----Suppliers-----
Supplier Id        int64
Supplier Name     object
Contact Person    object
Phone Number      object
City              object
dtype: object

###### 4) Referential Integrity Validation

In [55]:
def check_fk(child_data,child_col,parent_data,parent_col):
    invalid=child_data[~child_data[child_col].isin(parent_data[parent_col])]

    if invalid.empty:
        print('Referential Integrity valid')
    else:
        print(f'len{invalid} invalid values found')

In [56]:
check_fk(sales_data,'Store Id',stores_data,'Store Id')
check_fk(sales_data,'Employee Id',employees_data,'Employee Id')
check_fk(sales_data,'Product Id',products_data,'Product Id')
check_fk(sales_data,'Customer Id',customer_data,'Customer Id')

Referential Integrity valid
Referential Integrity valid
Referential Integrity valid
Referential Integrity valid

In [57]:
# Saving All Tables After Cleaning
sales_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\AllSales_Cleaned.csv", index=False)
customer_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\CustomerMaster_Cleaned.csv",index=False)
employees_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\Employees_Cleaned.csv",index=False) 
products_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\ProductCatalog_Cleaned.csv", index=False)
stock_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\Stock_Cleaned.csv", index=False)
prescriptions_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\Prescriptions_Cleaned.csv",index=False)
category_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\Categories_Cleaned.csv",index=False)
stores_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\Stores_Cleaned.csv",index=False)
suppliers_data.to_csv("F:\A7med els3eed\Digitara - Data Analysis\Health Retail Stores\Cleaned Data\Suppliers_Cleaned.csv",index=False)

I did the rest of the cleaning using the power Query